// Mocks generated by Mockito 5.4.6 from annotations
// in totp/test/widget/qr_scanner_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:totp/src/core/services/qr_code_processor_service.dart' as _i2;
import 'package:totp/src/features/totp_management/models/totp_item.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQrCodeProcessResult_0 extends _i1.SmartFake
    implements _i2.QrCodeProcessResult {
  _FakeQrCodeProcessResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QrCodeProcessorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQrCodeProcessorService extends _i1.Mock
    implements _i2.QrCodeProcessorService {
  MockQrCodeProcessorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.QrCodeProcessResult> processQrCode(String? qrData) =>
      (super.noSuchMethod(
            Invocation.method(#processQrCode, [qrData]),
            returnValue: _i3.Future<_i2.QrCodeProcessResult>.value(
              _FakeQrCodeProcessResult_0(
                this,
                Invocation.method(#processQrCode, [qrData]),
              ),
            ),
          )
          as _i3.Future<_i2.QrCodeProcessResult>);

  @override
  _i3.Future<void> addTotpItem(_i4.TotpItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addTotpItem, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
